libapi: forward-declare _mkdir to avoid <direct.h> conflicts
<direct.h> on mingw drags in <io.h> which prototypes open / lseek
/ read / write with stdio signatures and collides with this
file's PSX-shim implementations of the same names (which take
PSX-style argument types). Forward-declare _mkdir directly so we
get the prototype without the conflicts.

Build error introduced by d5c2d95 (MCD relocation):

  error: conflicting types for 'open'; have 'int(char *, unsigned int)'
  note: previous declaration of 'open' with type 'int(const char *, int, ...)'
  (and same for lseek / read / write)